# Generated by Django 5.0.6 on 2024-08-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='about',
            name='img2',
            field=models.ImageField(default=1, upload_to='imgs/About'),
            preserve_default=False,
        ),
    ]
